server:
  port: 8080

spring:
  kafka:
    bootstrap-servers: prod-kafka.company.com:9092

  data:
    mongodb:
      uri: mongodb://prod-mongo.company.com:27017/scheduling_db
      database: scheduling_db
      auto-index-creation: true

app:
  environment: prod

logging:
  level:
    root: WARN

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
